name: CI - Deploy to Hugging Face Space

on: # Trigger workflows on events
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Clone the Hugging Face Space
      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: git clone https://huggingface.co/spaces/Jsanchez759/text_summary space_repo
        
      - name: Configure Git Identity
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "GitHub Actions Bot"

      # Step 4: Commit and push changes to Hugging Face Space
      - name: Commit and Push Changes
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: git push --force https://huggingface.co/spaces/Jsanchez759/text_summary main
          # git add -u
          # git commit -m "Deploy updated files to Hugging Face Space"
          
