name: CI - Deploy to Hugging Face Space

on: # Trigger workflows on events
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Clone the Hugging Face Space
      - name: Clone Hugging Face Space
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://huggingface.co/spaces/Jsanchez759/text_summary
        
      - name: Configure Git Identity
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "GitHub Actions Bot"

      # Step 4: Commit and push changes to Hugging Face Space
      - name: Commit and Push Changes
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: git push --force https://Jsanchez759:$HF_TOKEN@huggingface.co/spaces/Jsanchez759/text_summary main
        #git push --force https://$HF@huggingface.co/spaces/Jsanchez759/text_summary main
          # git add -u
          # git commit -m "Deploy updated files to Hugging Face Space"
          
